import type { UIStyle } from '../types';

export const UI_STYLES: UIStyle[] = [
  {
    id: 1,
    name: "Neo Brutalism",
    fonts: { primary: "Inter", secondary: "Space Mono" },
    colors: { primary: "Neon green", accent: "Electric blue", dark: "Black", light: "Pure white" },
    layout: "Blocky, grid-based, little padding, raw edges",
    style: "Harsh contrast, minimal shadows, sharp corners",
    previewConfig: {
      palette: { bg: "#FFFFFF", text: "#000000", primary: "#39FF14", accent: "#00FFFF", neutral: "#F0F0F0" },
      buttonClasses: "bg-[#39FF14] text-black font-bold py-2 px-4 border-2 border-black rounded-none hover:bg-[#00FFFF] hover:text-black active:translate-x-[2px] active:translate-y-[2px] active:shadow-none transition-all duration-150 shadow-[4px_4px_0px_#000000] hover:shadow-[2px_2px_0px_#000000]",
      cardClasses: "bg-white border-2 border-black p-4 md:p-6 rounded-none",
      cardPrimaryClasses: "bg-[#00FFFF] text-black border-2 border-black p-6 rounded-none shadow-[6px_6px_0px_#000000]",
      containerClasses: "bg-white",
      headerClasses: "font-black text-4xl tracking-tighter",
      tagClasses: "text-black text-xs font-bold px-3 py-1 rounded-none border-2 border-black",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 border-2 border-black rounded-none hover:bg-[#FFFF00]",
      inputClasses: "bg-white border-2 border-black rounded-none placeholder:text-black/50 text-sm p-2 w-full",
      tabClasses: { container: "border-b-2 border-black", base: "px-4 py-2 text-sm font-bold", active: "bg-black text-white", inactive: "hover:bg-gray-200" },
      kpiCardClasses: "bg-white border-2 border-black p-4 rounded-none shadow-[4px_4px_0px_#000000]",
      avatarClasses: "w-9 h-9 rounded-none border-2 border-black",
    },
  },
  {
    id: 2,
    name: "Cyber Y2K Retro",
    fonts: { primary: "Orbitron", secondary: "Saira Stencil One" },
    colors: { primary: "Chrome", accent: "Deep purple", dark: "Metallic silver", light: "Acid green" },
    layout: "Glassy buttons, techy interface, glowing frames",
    style: "Techno-futuristic with grunge pixel patterns",
    previewConfig: {
      palette: { bg: "#1a0035", text: "#e0e0e0", primary: "#c0c0c0", accent: "#9d00ff", neutral: "rgba(255,255,255,0.05)" },
      buttonClasses: "bg-white/10 backdrop-blur-sm border border-purple-400/50 text-purple-300 font-bold rounded-full px-6 py-2 hover:bg-purple-500/30 hover:text-white transition-all duration-300 shadow-[0_0_15px_rgba(157,0,255,0.5)]",
      cardClasses: "bg-black/30 backdrop-blur-md border border-purple-500/50 rounded-lg p-4 md:p-6 shadow-2xl shadow-purple-900/50",
      cardPrimaryClasses: "bg-purple-900/50 backdrop-blur-md border border-purple-400/50 rounded-lg p-6 shadow-2xl shadow-purple-900/50",
      containerClasses: "bg-gradient-to-br from-[#1a0035] to-[#000000]",
      headerClasses: "font-black text-4xl text-purple-300 drop-shadow-[0_0_8px_rgba(157,0,255,0.7)]",
      tagClasses: "bg-pink-500/50 text-pink-200 text-xs font-bold px-3 py-1 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/10 rounded-full border border-purple-400/50 text-purple-300 hover:bg-purple-500/30",
      inputClasses: "bg-black/20 border border-purple-500/50 rounded-md placeholder:text-purple-300/50 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-purple-500/50", base: "px-4 py-2 text-sm text-purple-300", active: "bg-purple-500/30", inactive: "hover:bg-purple-500/10" },
      kpiCardClasses: "bg-black/30 backdrop-blur-md border border-purple-500/50 rounded-lg p-4",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-purple-500/80",
    },
  },
    {
    id: 3,
    name: "Japanese Minimal Zen",
    fonts: { primary: "Noto Serif JP", secondary: "Zen Maru Gothic" },
    colors: { primary: "Rice paper white", accent: "Ink black", dark: "Red accents", light: "Pine green" },
    layout: "Vertical scroll, whitespace-heavy, floating boxes",
    style: "Natural textures, elegant typography",
    previewConfig: {
      palette: { bg: "#F5F5DC", text: "#333333", primary: "#BC002D", accent: "#006400", neutral: "#FFFFFF" },
      buttonClasses: "bg-transparent border border-[#BC002D] text-[#BC002D] font-bold px-6 py-2 rounded-sm hover:bg-[#BC002D] hover:text-white transition-colors duration-300",
      cardClasses: "bg-white/80 p-4 md:p-6 rounded-md shadow-sm border border-black/5",
      cardPrimaryClasses: "bg-[#BC002D] text-white p-6 rounded-md shadow-sm",
      containerClasses: "bg-[#F5F5DC]",
      headerClasses: "font-bold text-4xl text-[#111111]",
      tagClasses: "bg-[#006400] text-white text-xs font-semibold px-3 py-1 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 rounded-md border border-gray-300 hover:bg-gray-100",
      inputClasses: "bg-white/80 border border-gray-300 rounded-md placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-600", active: "border-b-2 border-black text-black", inactive: "hover:bg-gray-100" },
      kpiCardClasses: "bg-white/80 p-4 rounded-md shadow-sm border border-black/5",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 4,
    name: "Digital Punk Vaporwave",
    fonts: { primary: "VT323", secondary: "Major Mono Display" },
    colors: { primary: "Magenta", accent: "Cyan", dark: "Teal", light: "Pastel gradients" },
    layout: "VHS-style cards, pixel buttons, retro grids",
    style: "80s aesthetic, surreal, distorted glows",
    previewConfig: {
      palette: { bg: "#0d0221", text: "#00f7ff", primary: "#ff00c1", accent: "#00f7ff", neutral: "#26174a" },
      buttonClasses: "bg-[#ff00c1] text-white text-2xl px-6 py-1 rounded-none border-2 border-[#00f7ff] shadow-[3px_3px_0px_#00f7ff] hover:bg-transparent hover:text-[#00f7ff] transition-all",
      cardClasses: "bg-gradient-to-b from-[#26174a] to-[#0d0221] p-4 border border-[#ff00c1]",
      cardPrimaryClasses: "bg-gradient-to-b from-[#ff00c1] to-[#ad0086] p-4 border border-[#00f7ff]",
      containerClasses: "bg-[#0d0221]",
      headerClasses: "text-6xl text-center text-[#ff00c1] drop-shadow-[3px_3px_0px_#00f7ff]",
      tagClasses: "bg-cyan-400 text-black text-lg px-3 py-0",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 border-2 border-[#00f7ff] text-[#00f7ff] hover:bg-[#ff00c1]/50",
      inputClasses: "bg-black/50 border-2 border-[#00f7ff] placeholder:text-[#00f7ff]/50 text-[#00f7ff] text-xl p-2 w-full",
      tabClasses: { container: "border-b-2 border-[#ff00c1]", base: "px-4 py-2 text-xl text-[#00f7ff]", active: "bg-[#ff00c1] text-black", inactive: "hover:bg-[#ff00c1]/20" },
      kpiCardClasses: "bg-black/50 p-4 border-2 border-[#ff00c1]",
      avatarClasses: "w-9 h-9 rounded-none border-2 border-[#00f7ff]",
    },
  },
    {
    id: 5,
    name: "Modern Swiss Grid",
    fonts: { primary: "Inter", secondary: "Inter" },
    colors: { primary: "Red", accent: "White", dark: "Charcoal gray", light: "Yellow" },
    layout: "Modular strict grid, bold sections",
    style: "Clean, structured, information-dominant",
    previewConfig: {
      palette: { bg: "#f0f0f0", text: "#111111", primary: "#FF0000", accent: "#FFFF00", neutral: "#ffffff" },
      buttonClasses: "bg-[#FF0000] text-white font-bold py-3 px-8 rounded-none hover:bg-black transition-colors",
      cardClasses: "bg-white p-4 md:p-6 rounded-none",
      cardPrimaryClasses: "bg-[#FF0000] text-white p-6 rounded-none",
      containerClasses: "bg-[#f0f0f0]",
      headerClasses: "font-black text-6xl uppercase tracking-tighter",
      tagClasses: "bg-[#111] text-white text-xs font-bold px-3 py-1.5 rounded-none",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-200 hover:bg-black hover:text-white rounded-none",
      inputClasses: "bg-white border border-gray-300 rounded-none placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "", base: "px-4 py-2 text-sm font-semibold uppercase", active: "bg-black text-white", inactive: "bg-gray-200 hover:bg-gray-300" },
      kpiCardClasses: "bg-white p-4 rounded-none",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 6,
    name: "Tech Minimal Future",
    fonts: { primary: "Inter", secondary: "IBM Plex Sans" },
    colors: { primary: "Slate gray", accent: "Cobalt blue", dark: "Soft white", light: "Transparent" },
    layout: "Collapsible panels, toggles, clean spacing",
    style: "Functional, airy, sharp UX",
    previewConfig: {
      palette: { bg: "#0B0E14", text: "#EAECEF", primary: "#3E63DD", accent: "#1D2330", neutral: "#1D2330" },
      buttonClasses: "bg-[#3E63DD] text-white font-semibold py-2 px-5 rounded-lg hover:bg-[#2a4db8] transition-colors",
      cardClasses: "bg-[#1D2330]/60 border border-gray-700/50 p-4 md:p-6 rounded-xl",
      cardPrimaryClasses: "bg-[#3E63DD] text-white p-6 rounded-xl",
      containerClasses: "bg-[#0B0E14]",
      headerClasses: "font-bold text-4xl text-white",
      tagClasses: "bg-[#3E63DD] text-white text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-[#1D2330] rounded-lg hover:bg-[#3E63DD]",
      inputClasses: "bg-transparent border border-gray-700/50 rounded-lg placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-700/50", base: "px-3 py-2 text-sm text-gray-400", active: "text-white", inactive: "hover:bg-gray-800/50 rounded-t-md" },
      kpiCardClasses: "bg-[#1D2330]/60 border border-gray-700/50 p-4 rounded-xl",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 7,
    name: "Digital Graffiti Streetwear",
    fonts: { primary: "Bungee", secondary: "Bebas Neue" },
    colors: { primary: "Safety orange", accent: "Matte black", dark: "Paint-splatter neon", light: "Gray" },
    layout: "Bold headers, sticker-like buttons, off-grid placement",
    style: "Energetic, urban, youth-driven",
    previewConfig: {
      palette: { bg: "#1a1a1a", text: "#ffffff", primary: "#FF6700", accent: "#39FF14", neutral: "#282828" },
      buttonClasses: "bg-[#FF6700] text-black text-2xl tracking-widest px-8 py-2 -skew-x-12 hover:skew-x-0 transition-transform",
      cardClasses: "bg-[#282828] p-4 md:p-6 border-4 border-dashed border-[#39FF14]",
      cardPrimaryClasses: "bg-[#FF6700] text-black p-6",
      containerClasses: "bg-[#1a1a1a]",
      headerClasses: "text-7xl text-white",
      tagClasses: "bg-[#39FF14] text-black text-xl px-4",
      iconButtonClasses: "flex items-center justify-center w-12 h-12 bg-white/10 border-2 border-white/50 -skew-x-12 hover:bg-white/20",
      inputClasses: "bg-transparent border-b-4 border-dotted border-white/50 text-2xl p-2 w-full text-center tracking-widest",
      tabClasses: { container: "border-4 border-dashed border-[#FF6700] p-1", base: "px-4 py-1 text-2xl -skew-x-12", active: "bg-[#FF6700] text-black", inactive: "hover:bg-white/20" },
      kpiCardClasses: "bg-[#282828] p-4 border-2 border-white/80",
      avatarClasses: "w-9 h-9 rounded-full border-4 border-dashed border-[#39FF14]",
    },
  },
    {
    id: 8,
    name: "Mystic Dream Pop",
    fonts: { primary: "Cormorant Garamond", secondary: "Manrope" },
    colors: { primary: "Lavender", accent: "Cosmic pink", dark: "Deep indigo", light: "Pearl" },
    layout: "Floating elements, parallax layers, dreamy textures",
    style: "Ethereal, feminine, surreal",
    previewConfig: {
      palette: { bg: "#2B0B3F", text: "#EADFF7", primary: "#C5A2D8", accent: "#FF6B97", neutral: "rgba(255,255,255,0.05)" },
      buttonClasses: "bg-gradient-to-r from-[#FF6B97] to-[#C5A2D8] text-white font-bold py-2 px-6 rounded-full shadow-lg hover:shadow-xl hover:scale-105 transition-all",
      cardClasses: "bg-white/10 backdrop-blur-lg p-4 md:p-6 rounded-2xl border border-white/20",
      cardPrimaryClasses: "bg-gradient-to-r from-[#FF6B97]/50 to-[#C5A2D8]/50 backdrop-blur-lg text-white p-6 rounded-2xl border border-white/20",
      containerClasses: "bg-gradient-to-br from-[#2B0B3F] via-[#4A2B5E] to-[#693C7E]",
      headerClasses: "font-bold text-5xl text-white",
      tagClasses: "bg-white/10 text-white text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/10 rounded-full hover:bg-white/20",
      inputClasses: "bg-white/5 backdrop-blur-sm border border-white/10 rounded-full placeholder:text-gray-400 text-sm p-2 px-4 w-full",
      tabClasses: { container: "", base: "px-4 py-2 text-sm rounded-full", active: "bg-white/10", inactive: "hover:bg-white/5" },
      kpiCardClasses: "bg-white/10 backdrop-blur-lg p-4 rounded-2xl border border-white/20",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-white/20",
    },
  },
  {
    id: 9,
    name: "Editorial Modern",
    fonts: { primary: "Playfair Display", secondary: "Inter" },
    colors: { primary: "Off-white", accent: "Black", dark: "Beige", light: "Soft gold" },
    layout: "Magazine-style columns, bold image breaks",
    style: "Sophisticated, timeless, serif-heavy",
    previewConfig: {
      palette: { bg: "#FDFCF7", text: "#222222", primary: "#BFA588", accent: "#000000", neutral: "#EFEBE3" },
      buttonClasses: "bg-transparent border border-black text-black font-semibold tracking-widest uppercase text-xs px-8 py-3 hover:bg-black hover:text-white transition-colors",
      cardClasses: "bg-transparent p-4 md:p-6",
      cardPrimaryClasses: "bg-[#222] text-white p-6",
      containerClasses: "bg-[#FDFCF7]",
      headerClasses: "font-black text-6xl text-black",
      tagClasses: "bg-gray-200 text-black text-xs px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-100 hover:bg-gray-200",
      inputClasses: "bg-transparent border-b border-gray-300 placeholder:text-gray-400 text-sm py-2 w-full focus:border-black",
      tabClasses: { container: "border-b border-gray-200", base: "px-1 py-2 text-sm tracking-widest uppercase", active: "border-b-2 border-black font-bold", inactive: "text-gray-500 hover:text-black" },
      kpiCardClasses: "bg-transparent p-4 border border-gray-200",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 10,
    name: "Playful UX Toybox",
    fonts: { primary: "Fredoka", secondary: "Poppins" },
    colors: { primary: "Sky blue", accent: "Canary yellow", dark: "Coral red", light: "Mint" },
    layout: "Rounded components, bouncy transitions",
    style: "Joyful, childlike, user-friendly",
    previewConfig: {
      palette: { bg: "#F0F8FF", text: "#4B5563", primary: "#38BDF8", accent: "#FBBF24", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#38BDF8] text-white font-bold text-lg py-3 px-6 rounded-full shadow-md hover:-translate-y-1 transition-all duration-300 ease-in-out",
      cardClasses: "bg-white p-4 md:p-8 rounded-3xl shadow-lg",
      cardPrimaryClasses: "bg-[#38BDF8] text-white p-8 rounded-3xl shadow-lg",
      containerClasses: "bg-[#F0F8FF]",
      headerClasses: "font-semibold text-5xl text-[#1F2937]",
      tagClasses: "bg-yellow-200 text-yellow-800 text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-12 h-12 bg-white rounded-2xl shadow-md hover:bg-gray-50",
      inputClasses: "bg-white border-2 border-gray-200 rounded-full placeholder:text-gray-400 text-sm p-2 px-4 w-full focus:border-blue-300",
      tabClasses: { container: "bg-white p-1 rounded-full shadow-inner", base: "px-4 py-1.5 text-sm font-semibold rounded-full", active: "bg-blue-100 text-blue-600", inactive: "text-gray-500 hover:bg-blue-50" },
      kpiCardClasses: "bg-white p-4 rounded-3xl shadow-lg",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 11,
    name: "Black & Neon Hacker UI",
    fonts: { primary: "JetBrains Mono", secondary: "Roboto Mono" },
    colors: { primary: "Terminal green", accent: "Matte black", dark: "Electric yellow", light: "Gray" },
    layout: "Code-style UI, toggles, grids",
    style: "Command-line meets dark mode dashboard",
    previewConfig: {
      palette: { bg: "#010101", text: "#00ff00", primary: "#ffff00", accent: "#00ff00", neutral: "#111111" },
      buttonClasses: "border border-[#00ff00] text-[#00ff00] px-4 py-1 text-sm hover:bg-[#00ff00]/20",
      cardClasses: "bg-[#111]/80 border border-gray-800 p-4",
      cardPrimaryClasses: "bg-[#ffff00] text-black p-4",
      containerClasses: "bg-black",
      headerClasses: "text-3xl text-[#00ff00]",
      tagClasses: "bg-[#00ff00] text-black text-xs font-bold px-2 py-0.5",
      iconButtonClasses: "flex items-center justify-center w-8 h-8 border border-gray-700 hover:bg-gray-800",
      inputClasses: "bg-transparent border border-gray-700 placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-700", base: "px-3 py-1 text-xs", active: "bg-[#00ff00] text-black", inactive: "hover:bg-gray-800" },
      kpiCardClasses: "bg-[#111]/80 border border-gray-800 p-4",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-gray-700",
    },
  },
  {
    id: 12,
    name: "Earthcore Organic",
    fonts: { primary: "DM Serif Display", secondary: "Public Sans" },
    colors: { primary: "Terracotta", accent: "Moss green", dark: "Sand", light: "Bark brown" },
    layout: "Rounded cards, texture backgrounds",
    style: "Natural, handmade, eco-inspired",
    previewConfig: {
      palette: { bg: "#F4F1E8", text: "#4C4A3E", primary: "#C87E6A", accent: "#6A8C6A", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#C87E6A] text-white font-bold py-2 px-6 rounded-lg hover:bg-[#b06a57] transition-colors",
      cardClasses: "bg-white/80 backdrop-blur-sm border border-black/5 p-4 md:p-6 rounded-xl",
      cardPrimaryClasses: "bg-[#6A8C6A] text-white p-6 rounded-xl",
      containerClasses: "bg-[#F4F1E8]",
      headerClasses: "font-bold text-5xl text-[#4C4A3E]",
      tagClasses: "bg-green-100 text-green-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white border border-gray-200 rounded-lg hover:bg-gray-50",
      inputClasses: "bg-white/80 border border-gray-200 rounded-lg placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-500", active: "text-[#4C4A3E] border-b-2 border-[#C87E6A]", inactive: "hover:bg-gray-50" },
      kpiCardClasses: "bg-white/80 backdrop-blur-sm border border-black/5 p-4 rounded-xl",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 13,
    name: "Art Deco Luxe",
    fonts: { primary: "Lustria", secondary: "Raleway" },
    colors: { primary: "Gold", accent: "Emerald", dark: "Ivory", light: "Black" },
    layout: "Bold geometry, decorative borders",
    style: "Vintage glam, symmetrical, elegant",
    previewConfig: {
      palette: { bg: "#1A1A1A", text: "#E5E5E5", primary: "#D4AF37", accent: "#009B77", neutral: "#2A2A2A" },
      buttonClasses: "bg-transparent border-2 border-[#D4AF37] text-[#D4AF37] font-bold tracking-widest uppercase text-xs px-8 py-3 hover:bg-[#D4AF37] hover:text-black transition-colors",
      cardClasses: "bg-[#2A2A2A] p-4 md:p-6 border-t-4 border-b-4 border-double border-[#D4AF37]/50",
      cardPrimaryClasses: "bg-gradient-to-r from-yellow-600 to-yellow-800 text-black p-6",
      containerClasses: "bg-[#1A1A1A]",
      headerClasses: "font-bold text-5xl text-center text-white tracking-widest uppercase",
      tagClasses: "bg-emerald-800 text-white text-xs font-semibold px-3 py-1.5 rounded-sm",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 border-2 border-[#D4AF37]/50 text-[#D4AF37] hover:bg-[#D4AF37]/10",
      inputClasses: "bg-transparent border-b-2 border-[#D4AF37]/50 placeholder:text-gray-500 text-sm py-2 w-full",
      tabClasses: { container: "border-b-2 border-double border-[#D4AF37]/50", base: "px-4 py-2 text-sm tracking-wider uppercase", active: "text-[#D4AF37] font-bold", inactive: "hover:bg-[#D4AF37]/10" },
      kpiCardClasses: "bg-[#2A2A2A] p-4 border-t-2 border-[#D4AF37]/50",
      avatarClasses: "w-9 h-9 rounded-sm border-2 border-[#D4AF37]/50",
    },
  },
  {
    id: 14,
    name: "Sci-Fi HUD Interface",
    fonts: { primary: "Exo 2", secondary: "Audiowide" },
    colors: { primary: "Holographic blue", accent: "Black", dark: "Neon red", light: "Transparent" },
    layout: "Circular UI, overlays, data rings",
    style: "Mission-control dashboard, immersive tech",
    previewConfig: {
      palette: { bg: "#03081D", text: "#7DF9FF", primary: "#00BFFF", accent: "#FF1D15", neutral: "rgba(0, 191, 255, 0.05)" },
      buttonClasses: "bg-cyan-500/10 border border-cyan-500/50 text-cyan-400 font-bold px-6 py-2 hover:bg-cyan-500/20",
      cardClasses: "bg-black/20 backdrop-blur-sm p-4 md:p-6 border border-cyan-500/30",
      cardPrimaryClasses: "bg-cyan-900/50 text-white p-6 border border-cyan-500/30",
      containerClasses: "bg-[#03081D]",
      headerClasses: "font-black text-4xl text-cyan-300 uppercase tracking-widest",
      tagClasses: "bg-red-500/20 text-red-300 text-xs px-3 py-1",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 border border-cyan-500/30 hover:bg-cyan-500/20",
      inputClasses: "bg-black/20 border border-cyan-500/30 placeholder:text-cyan-400/50 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-cyan-500/30", base: "px-4 py-2 text-sm uppercase", active: "bg-cyan-500/20", inactive: "hover:bg-cyan-500/10" },
      kpiCardClasses: "bg-black/20 backdrop-blur-sm p-4 border border-cyan-500/30",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-cyan-500/50",
    },
  },
  {
    id: 15,
    name: "Monochrome Editorial",
    fonts: { primary: "Playfair Display", secondary: "Inter" },
    colors: { primary: "Black", accent: "White", dark: "Grayscale", light: "Light gray" },
    layout: "Type-driven, large headlines, image overlays",
    style: "Modern, polished, luxury minimalist",
    previewConfig: {
      palette: { bg: "#FFFFFF", text: "#000000", primary: "#000000", accent: "#999999", neutral: "#F5F5F5" },
      buttonClasses: "bg-black text-white font-semibold tracking-wider text-sm px-8 py-3 hover:bg-gray-800 transition-colors",
      cardClasses: "bg-white p-4 md:p-6",
      cardPrimaryClasses: "bg-black text-white p-6",
      containerClasses: "bg-white",
      headerClasses: "font-black text-7xl text-black",
      tagClasses: "bg-gray-200 text-gray-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-100 hover:bg-gray-200",
      inputClasses: "bg-gray-100 border border-transparent rounded-md placeholder:text-gray-400 text-sm p-2 w-full focus:bg-white focus:border-gray-300",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm", active: "text-black font-semibold", inactive: "text-gray-500 hover:text-black" },
      kpiCardClasses: "bg-gray-50 p-4 rounded-lg",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 16,
    name: "Comic Pop",
    fonts: { primary: "Anton", secondary: "Comic Neue" },
    colors: { primary: "Bright primary colors", accent: "Dots", dark: "Halftones", light: "White" },
    layout: "Panels, action cards, thick borders",
    style: "Playful, bold, story-driven",
    previewConfig: {
      palette: { bg: "#FFFF00", text: "#000000", primary: "#FF0000", accent: "#0000FF", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#0000FF] text-white font-bold text-lg py-2 px-6 rounded-lg border-2 border-black hover:bg-blue-700 transform hover:scale-105",
      cardClasses: "bg-white p-4 md:p-6 rounded-lg border-4 border-black",
      cardPrimaryClasses: "bg-[#FF0000] text-white p-6 rounded-lg border-4 border-black",
      containerClasses: "bg-yellow-300",
      headerClasses: "font-black text-6xl text-black uppercase -rotate-2",
      tagClasses: "bg-blue-500 text-white text-xs font-bold px-3 py-1.5 rounded-full border-2 border-black",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white border-2 border-black rounded-full hover:bg-gray-200",
      inputClasses: "bg-white border-2 border-black rounded-lg placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b-4 border-black", base: "px-4 py-2 text-lg font-bold", active: "bg-red-500 text-white border-2 border-black -mb-[6px]", inactive: "hover:bg-blue-200" },
      kpiCardClasses: "bg-white p-4 rounded-lg border-4 border-black",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-black",
    },
  },
  {
    id: 17,
    name: "Ethereal Cloud UI",
    fonts: { primary: "Raleway", secondary: "Inter" },
    colors: { primary: "Sky blue", accent: "Cloud white", dark: "Blush pink", light: "Transparent" },
    layout: "Soft shadows, fluid animations",
    style: "Dreamy SaaS style, calm experience",
    previewConfig: {
      palette: { bg: "#F0F9FF", text: "#374151", primary: "#60A5FA", accent: "#FBCFE8", neutral: "#FFFFFF" },
      buttonClasses: "bg-blue-500 text-white font-semibold py-2 px-5 rounded-lg shadow-sm hover:bg-blue-600 transition-colors",
      cardClasses: "bg-white/70 backdrop-blur-xl p-4 md:p-6 rounded-xl shadow-lg shadow-blue-100/50",
      cardPrimaryClasses: "bg-blue-500 text-white p-6 rounded-xl shadow-lg",
      containerClasses: "bg-[#F0F9FF]",
      headerClasses: "font-bold text-4xl text-gray-800",
      tagClasses: "bg-pink-100 text-pink-700 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white rounded-lg shadow-sm hover:bg-gray-50",
      inputClasses: "bg-white/80 border border-gray-200 rounded-lg placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-500", active: "text-blue-500 border-b-2 border-blue-500", inactive: "hover:text-blue-500" },
      kpiCardClasses: "bg-white/70 backdrop-blur-xl p-4 rounded-xl shadow-lg shadow-blue-100/50",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 18,
    name: "Luxury Black & Gold",
    fonts: { primary: "Playfair Display", secondary: "Quattrocento" },
    colors: { primary: "Jet black", accent: "Gold foil", dark: "Deep navy", light: "White" },
    layout: "Hero image focus, elegant spacing",
    style: "Rich, high-end, premium experience",
    previewConfig: {
      palette: { bg: "#000000", text: "#E5E5E5", primary: "#D4AF37", accent: "#000C1F", neutral: "#1A1A1A" },
      buttonClasses: "bg-gradient-to-r from-yellow-500 to-yellow-600 text-black font-bold py-3 px-8 rounded-sm hover:from-yellow-600 hover:to-yellow-700",
      cardClasses: "bg-transparent border border-yellow-800/50 p-4 md:p-6",
      cardPrimaryClasses: "bg-[#1A1A1A] text-white p-6 border-t-2 border-yellow-600",
      containerClasses: "bg-black",
      headerClasses: "font-black text-6xl text-white",
      tagClasses: "bg-yellow-900/50 text-yellow-300 text-xs px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 border border-yellow-800/50 text-yellow-500 hover:bg-yellow-900/50",
      inputClasses: "bg-transparent border-b border-yellow-800/50 placeholder:text-gray-600 py-2 w-full",
      tabClasses: { container: "border-b border-yellow-800/50", base: "px-4 py-2 text-sm text-gray-400", active: "text-yellow-400 font-bold", inactive: "hover:text-white" },
      kpiCardClasses: "bg-transparent border border-yellow-800/50 p-4",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 19,
    name: "PixelArt Retro",
    fonts: { primary: "Press Start 2P", secondary: "VT323" },
    colors: { primary: "Primary pixel palette", accent: "Chunky colors", dark: "Black", light: "White" },
    layout: "Blocky UI, pixel transitions",
    style: "Retro gaming, nostalgic charm",
    previewConfig: {
      palette: { bg: "#222034", text: "#FFFFFF", primary: "#32CD32", accent: "#FF0000", neutral: "#45283c" },
      buttonClasses: "bg-[#32CD32] text-black text-sm px-4 py-2 hover:bg-lime-400",
      cardClasses: "bg-[#45283c] p-4",
      cardPrimaryClasses: "bg-[#32CD32] text-black p-4",
      containerClasses: "bg-[#222034]",
      headerClasses: "text-2xl text-lime-300",
      tagClasses: "bg-red-500 text-white text-xs px-2 py-0.5",
      iconButtonClasses: "flex items-center justify-center w-8 h-8 bg-gray-600 hover:bg-gray-500",
      inputClasses: "bg-black/50 border border-gray-500 placeholder:text-gray-400 text-lg p-2 w-full",
      tabClasses: { container: "border-b-4 border-gray-600", base: "px-2 py-1 text-sm", active: "bg-gray-600", inactive: "hover:bg-gray-700" },
      kpiCardClasses: "bg-[#45283c] p-4",
      avatarClasses: "w-9 h-9 rounded-none",
    },
  },
  {
    id: 20,
    name: "AI-Tech Glassmorphism",
    fonts: { primary: "Spline Sans", secondary: "Inter" },
    colors: { primary: "Frosted white", accent: "Purples", dark: "Gradients", light: "Transparency" },
    layout: "Blur panels, floating nav, glowing cards",
    style: "Ultra-modern, futuristic, floating interface",
    previewConfig: {
      palette: { bg: "#05021E", text: "#EBEBFF", primary: "#8A2BE2", accent: "#32CD32", neutral: "rgba(255,255,255,0.05)" },
      buttonClasses: "bg-white/10 backdrop-blur-md text-white font-semibold px-5 py-2 rounded-lg border border-white/20 hover:bg-white/20 transition-colors",
      cardClasses: "bg-white/5 backdrop-blur-xl border border-white/10 p-4 md:p-6 rounded-2xl",
      cardPrimaryClasses: "bg-gradient-to-r from-purple-600/50 to-blue-500/50 text-white p-6 rounded-2xl border border-white/10",
      containerClasses: "bg-[#05021E]",
      headerClasses: "font-bold text-4xl text-white",
      tagClasses: "bg-lime-500/20 text-lime-300 text-xs px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/5 rounded-lg border border-white/10 hover:bg-white/10",
      inputClasses: "bg-white/5 border border-white/10 rounded-lg placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-white/10", base: "px-4 py-2 text-sm text-gray-300", active: "text-white border-b-2 border-white", inactive: "hover:text-white" },
      kpiCardClasses: "bg-white/5 backdrop-blur-xl border border-white/10 p-4 rounded-2xl",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 21,
    name: "Origami Fold UI",
    fonts: { primary: "Noto Sans JP", secondary: "Inter" },
    colors: { primary: "Soft paper white", accent: "Pastel origami hues", dark: "Coral accents", light: "Light gray" },
    layout: "Angular panels folding over each other",
    style: "Geometric yet delicate, inspired by folded paper",
    previewConfig: {
      palette: { bg: "#F8F7F2", text: "#3D3D3D", primary: "#FF7F50", accent: "#87CEEB", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#FF7F50] text-white font-bold py-2 px-6 hover:bg-coral-600 transition-colors",
      cardClasses: "bg-white p-4 md:p-6 shadow-[5px_5px_0px_#EAE7DC]",
      cardPrimaryClasses: "bg-[#87CEEB] text-white p-6 shadow-[5px_5px_0px_#D0E0E8]",
      containerClasses: "bg-[#F8F7F2]",
      headerClasses: "font-bold text-4xl",
      tagClasses: "bg-coral-100 text-coral-800 text-xs font-semibold px-3 py-1.5 rounded-sm",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white shadow-[2px_2px_0px_#EAE7DC] hover:bg-gray-50",
      inputClasses: "bg-white border-b-2 border-gray-200 placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm", active: "font-bold text-[#FF7F50]", inactive: "text-gray-500 hover:text-black" },
      kpiCardClasses: "bg-white p-4 shadow-[3px_3px_0px_#EAE7DC]",
      avatarClasses: "w-9 h-9 rounded-sm",
    },
  },
  {
    id: 22,
    name: "Bioluminescent Night UI",
    fonts: { primary: "Orbitron", secondary: "IBM Plex Sans" },
    colors: { primary: "Midnight black", accent: "Glowing teal", dark: "Neon coral", light: "Violet" },
    layout: "Dark mode, glowing interactive elements",
    style: "Inspired by deep-sea creatures, luminous & surreal",
    previewConfig: {
      palette: { bg: "#000318", text: "#B4CFF2", primary: "#00F0FF", accent: "#FF5E5E", neutral: "rgba(0, 240, 255, 0.05)" },
      buttonClasses: "bg-transparent border border-[#00F0FF] text-[#00F0FF] font-bold px-6 py-2 rounded-sm shadow-[0_0_10px_#00F0FF] hover:bg-[#00F0FF] hover:text-black transition-all",
      cardClasses: "bg-black/30 backdrop-blur-md border border-[#00F0FF]/30 p-4 md:p-6 rounded-lg",
      cardPrimaryClasses: "bg-gradient-to-r from-teal-900/50 to-blue-900/50 text-white p-6 border border-[#00F0FF]/30",
      containerClasses: "bg-[#000318]",
      headerClasses: "font-black text-4xl text-white drop-shadow-[0_0_5px_#00F0FF]",
      tagClasses: "bg-red-500/30 text-red-300 text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/5 rounded-full border border-[#00F0FF]/30 text-[#00F0FF] hover:bg-white/10",
      inputClasses: "bg-black/20 border border-[#00F0FF]/30 rounded-md placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-[#00F0FF]/30", base: "px-4 py-2 text-sm", active: "text-[#00F0FF] shadow-[inset_0_-2px_4px_rgba(0,240,255,0.3)]", inactive: "text-gray-400 hover:text-white" },
      kpiCardClasses: "bg-black/30 backdrop-blur-md border border-[#00F0FF]/30 p-4 rounded-lg",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-[#00F0FF]/50",
    },
  },
  {
    id: 23,
    name: "Crystal Shard UI",
    fonts: { primary: "Spline Sans", secondary: "Inter" },
    colors: { primary: "Frosted white", accent: "Gemstone blue", dark: "Amethyst", light: "Glass gray" },
    layout: "Shattered crystal card grids",
    style: "Sharp edges, refracted-glass feel",
    previewConfig: {
      palette: { bg: "#E8EBF7", text: "#2C3A61", primary: "#4D72DE", accent: "#8A4DE8", neutral: "rgba(255,255,255,0.7)" },
      buttonClasses: "bg-white/50 backdrop-blur-lg border border-white/70 text-blue-900 font-bold px-6 py-2 hover:bg-white transition-colors",
      cardClasses: "bg-white/40 backdrop-blur-xl p-4 md:p-6 border border-white/50",
      cardPrimaryClasses: "bg-blue-500/80 text-white p-6",
      containerClasses: "bg-gradient-to-br from-blue-100 to-purple-100",
      headerClasses: "font-bold text-4xl text-indigo-900",
      tagClasses: "bg-purple-200 text-purple-800 text-xs font-semibold px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/40 backdrop-blur-md hover:bg-white/80",
      inputClasses: "bg-white/50 border border-white/70 rounded-md placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-white/50", base: "px-4 py-2 text-sm", active: "text-blue-700 font-bold", inactive: "text-gray-600 hover:text-black" },
      kpiCardClasses: "bg-white/40 backdrop-blur-xl p-4 border border-white/50",
      avatarClasses: "w-9 h-9 rounded-md",
    },
  },
  {
    id: 24,
    name: "Tactile Fabric UI",
    fonts: { primary: "DM Serif Display", secondary: "Inter" },
    colors: { primary: "Denim blue", accent: "Linen beige", dark: "Earthy brown", light: "White" },
    layout: "Soft textures, stitched edges, textile patterns",
    style: "Handmade, cozy, textile-inspired",
    previewConfig: {
      palette: { bg: "#EAE2D7", text: "#5C4B3E", primary: "#4A6E8A", accent: "#D4B79E", neutral: "#F5F0E9" },
      buttonClasses: "bg-[#4A6E8A] text-white font-bold py-2 px-6 rounded-md shadow-sm hover:bg-blue-800",
      cardClasses: "bg-[#F5F0E9] p-4 md:p-6 rounded-lg border-2 border-dashed border-gray-300",
      cardPrimaryClasses: "bg-[#D4B79E] text-[#5C4B3E] p-6 rounded-lg border-2 border-dashed border-gray-400",
      containerClasses: "bg-[#EAE2D7]",
      headerClasses: "font-bold text-5xl",
      tagClasses: "bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white border border-gray-300 rounded-lg hover:bg-gray-50",
      inputClasses: "bg-white border-2 border-gray-300 rounded-md placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b-2 border-dashed border-gray-300", base: "px-4 py-2 text-sm", active: "font-bold text-[#4A6E8A]", inactive: "text-gray-500 hover:text-black" },
      kpiCardClasses: "bg-[#F5F0E9] p-4 rounded-lg border-2 border-dashed border-gray-300",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 25,
    name: "Space Noir UI",
    fonts: { primary: "Bebas Neue", secondary: "Inter" },
    colors: { primary: "Black", accent: "Muted red", dark: "Steel blue", light: "Soft white" },
    layout: "Cinematic panels, widescreen cards",
    style: "Sci-fi meets noir detective aesthetics",
    previewConfig: {
      palette: { bg: "#101218", text: "#BCC5D4", primary: "#C93434", accent: "#4A6E8A", neutral: "#1A1D25" },
      buttonClasses: "bg-[#C93434] text-white tracking-widest uppercase text-sm px-8 py-3 hover:bg-red-700 transition-colors",
      cardClasses: "bg-[#1A1D25] p-4 md:p-6",
      cardPrimaryClasses: "bg-[#4A6E8A] text-white p-6",
      containerClasses: "bg-[#101218]",
      headerClasses: "font-black text-5xl text-white uppercase tracking-[0.2em]",
      tagClasses: "bg-red-900/50 text-red-300 text-xs px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-800/50 hover:bg-gray-700/50",
      inputClasses: "bg-transparent border-b border-gray-700 placeholder:text-gray-500 text-sm py-2 w-full",
      tabClasses: { container: "border-b border-gray-700", base: "px-4 py-2 text-sm uppercase tracking-wider", active: "text-white font-bold", inactive: "text-gray-500 hover:text-white" },
      kpiCardClasses: "bg-[#1A1D25] p-4",
      avatarClasses: "w-9 h-9 rounded-sm",
    },
  },
  {
    id: 26,
    name: "Prism Light UI",
    fonts: { primary: "Poppins", secondary: "Raleway" },
    colors: { primary: "Iridescent pastel gradients", accent: "White base", dark: "Transparent sections", light: "Soft gray" },
    layout: "Floating cards, transparent sections",
    style: "Minimal + dreamy prism reflection",
    previewConfig: {
      palette: { bg: "#F6F7FB", text: "#4A5568", primary: "#8A4DE8", accent: "#4D72DE", neutral: "rgba(255,255,255,0.8)" },
      buttonClasses: "bg-gradient-to-r from-purple-500 to-blue-500 text-white font-semibold py-2 px-6 rounded-lg shadow-md hover:shadow-lg transition-shadow",
      cardClasses: "bg-white/60 backdrop-blur-lg p-4 md:p-6 rounded-xl border border-white/50",
      cardPrimaryClasses: "bg-white/80 p-6 rounded-xl",
      containerClasses: "bg-[#F6F7FB]",
      headerClasses: "font-bold text-4xl text-gray-800",
      tagClasses: "bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/80 rounded-lg hover:bg-white",
      inputClasses: "bg-white/80 border border-gray-200 rounded-lg placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm", active: "font-bold text-purple-600", inactive: "text-gray-500 hover:text-black" },
      kpiCardClasses: "bg-white/60 backdrop-blur-lg p-4 rounded-xl border border-white/50",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 27,
    name: "Botanical Garden UI",
    fonts: { primary: "Lora", secondary: "Josefin Sans" },
    colors: { primary: "Sage green", accent: "Blush pink", dark: "Soil brown", light: "Cream" },
    layout: "Floral patterns, leafy dividers",
    style: "Elegant, organic, nature-rich",
    previewConfig: {
      palette: { bg: "#F0EFEA", text: "#5C4033", primary: "#8A9A5B", accent: "#E6BFB2", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#8A9A5B] text-white font-semibold py-2 px-5 rounded-md hover:bg-[#71834A] transition-colors",
      cardClasses: "bg-white/80 backdrop-blur-sm p-4 md:p-6 rounded-lg border border-black/5",
      cardPrimaryClasses: "bg-[#E6BFB2] text-[#5C4033] p-6 rounded-lg",
      containerClasses: "bg-[#F0EFEA]",
      headerClasses: "font-bold text-4xl text-[#5C4033]",
      tagClasses: "bg-green-100 text-green-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white border border-gray-200 rounded-lg hover:bg-gray-50",
      inputClasses: "bg-white border border-gray-200 rounded-md placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-500", active: "text-[#8A9A5B] border-b-2 border-[#8A9A5B]", inactive: "hover:bg-gray-50" },
      kpiCardClasses: "bg-white/80 p-4 rounded-lg border border-black/5",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 28,
    name: "Desert Mirage UI",
    fonts: { primary: "Abril Fatface", secondary: "Manrope" },
    colors: { primary: "Sand beige", accent: "Sunset orange", dark: "Turquoise", light: "Desert gold" },
    layout: "Wavy separators, heat shimmer animation",
    style: "Surreal desert oasis aesthetic",
    previewConfig: {
      palette: { bg: "#FDF6E3", text: "#654321", primary: "#FD5E53", accent: "#40E0D0", neutral: "#FAEBD7" },
      buttonClasses: "bg-gradient-to-r from-orange-500 to-red-500 text-white font-bold py-2 px-6 rounded-full shadow-md hover:shadow-lg transition-shadow",
      cardClasses: "bg-white/70 backdrop-blur-md p-4 md:p-6 rounded-xl",
      cardPrimaryClasses: "bg-[#40E0D0] text-white p-6 rounded-xl",
      containerClasses: "bg-[#FDF6E3]",
      headerClasses: "font-black text-5xl text-[#654321]",
      tagClasses: "bg-turquoise-100 text-turquoise-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/50 rounded-full hover:bg-white",
      inputClasses: "bg-white/70 border border-gray-200 rounded-full px-4 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-orange-200", base: "px-4 py-2 text-sm text-gray-600", active: "text-red-600 font-bold", inactive: "hover:text-red-500" },
      kpiCardClasses: "bg-white/70 p-4 rounded-xl",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 29,
    name: "Retro Futurism UI",
    fonts: { primary: "Exo 2", secondary: "Archivo" },
    colors: { primary: "Atomic orange", accent: "Teal", dark: "Chrome silver", light: "Black" },
    layout: "Jet-age curves, sci-fi dashboard",
    style: "60s future vision, playful retro",
    previewConfig: {
      palette: { bg: "#E5E5E5", text: "#222222", primary: "#FF6700", accent: "#008080", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#FF6700] text-white font-bold py-2 px-6 rounded-full hover:bg-orange-600",
      cardClasses: "bg-white p-4 md:p-6 rounded-2xl shadow-lg",
      cardPrimaryClasses: "bg-[#008080] text-white p-6 rounded-2xl",
      containerClasses: "bg-[#E5E5E5]",
      headerClasses: "font-black text-4xl uppercase text-gray-800",
      tagClasses: "bg-teal-200 text-teal-800 text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-12 h-12 bg-white rounded-full shadow-md",
      inputClasses: "bg-white border-2 border-gray-300 rounded-full px-4 text-sm p-2 w-full",
      tabClasses: { container: "bg-white p-1 rounded-full", base: "px-4 py-1 text-sm font-semibold rounded-full", active: "bg-orange-200 text-orange-800", inactive: "hover:bg-gray-100" },
      kpiCardClasses: "bg-white p-4 rounded-2xl shadow-lg",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 30,
    name: "Liquid Metal UI",
    fonts: { primary: "Inter", secondary: "Inter" },
    colors: { primary: "Polished chrome", accent: "Molten silver", dark: "Black", light: "White" },
    layout: "Fluid metallic buttons, reflective surfaces",
    style: "Glossy, futuristic, immersive",
    previewConfig: {
      palette: { bg: "#111111", text: "#FFFFFF", primary: "#B0B0B0", accent: "#FFFFFF", neutral: "#222222" },
      buttonClasses: "bg-gradient-to-b from-gray-300 to-gray-500 text-black font-semibold py-2 px-5 rounded-lg shadow-md border border-gray-600 hover:from-gray-400 hover:to-gray-600",
      cardClasses: "bg-gradient-to-b from-gray-800 to-gray-900 border border-gray-700 p-4 md:p-6 rounded-xl",
      cardPrimaryClasses: "bg-gray-700 text-white p-6 rounded-xl",
      containerClasses: "bg-[#111111]",
      headerClasses: "font-bold text-4xl text-white",
      tagClasses: "bg-gray-600 text-white text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-800 rounded-lg border border-gray-700",
      inputClasses: "bg-gray-900 border border-gray-700 rounded-lg placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-700", base: "px-4 py-2 text-sm text-gray-400", active: "text-white", inactive: "hover:bg-gray-800" },
      kpiCardClasses: "bg-gray-800/50 p-4 rounded-xl border border-gray-700",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 31,
    name: "Solar Eclipse UI",
    fonts: { primary: "Manrope", secondary: "Inter" },
    colors: { primary: "Black", accent: "Golden yellow", dark: "Twilight blue", light: "Crimson" },
    layout: "Circular modules, gradient light rings",
    style: "Celestial, cosmic interface",
    previewConfig: {
      palette: { bg: "#000000", text: "#FFFFFF", primary: "#FFD700", accent: "#FF4500", neutral: "#191970" },
      buttonClasses: "bg-transparent border-2 border-yellow-400 text-yellow-400 font-bold px-6 py-2 rounded-full shadow-[0_0_10px_#FFD700] hover:bg-yellow-400 hover:text-black transition-all",
      cardClasses: "bg-blue-900/30 backdrop-blur-md border border-yellow-400/30 p-4 md:p-6 rounded-full",
      cardPrimaryClasses: "bg-yellow-400 text-black p-6 rounded-full",
      containerClasses: "bg-black",
      headerClasses: "font-black text-4xl text-white drop-shadow-[0_0_5px_#FFD700]",
      tagClasses: "bg-red-500/30 text-red-300 text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/5 rounded-full border border-yellow-400/30",
      inputClasses: "bg-black/20 border border-yellow-400/30 rounded-full px-4 placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-yellow-400/30", base: "px-4 py-2 text-sm rounded-full", active: "bg-yellow-400/20 text-yellow-300", inactive: "text-gray-400 hover:text-white" },
      kpiCardClasses: "bg-blue-900/30 p-4 rounded-full border border-yellow-400/30",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-yellow-400/50",
    },
  },
    {
    id: 32,
    name: "Candy Pop UI",
    fonts: { primary: "Baloo 2", secondary: "Fredoka" },
    colors: { primary: "Bubblegum pink", accent: "Lemon yellow", dark: "Mint green", light: "Sky blue" },
    layout: "Rounded bubbly elements, candy-like buttons",
    style: "Playful, childlike, cheerful",
    previewConfig: {
      palette: { bg: "#F0F9FF", text: "#4B5563", primary: "#F9A8D4", accent: "#FDE047", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#F9A8D4] text-pink-800 font-bold text-lg py-3 px-6 rounded-full shadow-lg border-2 border-white hover:-translate-y-1 transition-all",
      cardClasses: "bg-white p-6 rounded-3xl shadow-2xl",
      cardPrimaryClasses: "bg-[#FDE047] text-yellow-800 p-6 rounded-3xl shadow-2xl",
      containerClasses: "bg-sky-100",
      headerClasses: "font-extrabold text-5xl text-gray-700",
      tagClasses: "bg-green-200 text-green-800 text-sm font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-12 h-12 bg-white rounded-2xl shadow-lg",
      inputClasses: "bg-white border-2 border-gray-200 rounded-full placeholder:text-gray-400 text-md p-2 px-4 w-full",
      tabClasses: { container: "bg-white p-1 rounded-full shadow-inner", base: "px-4 py-1.5 text-md font-bold rounded-full", active: "bg-pink-100 text-pink-600", inactive: "text-gray-500 hover:bg-pink-50" },
      kpiCardClasses: "bg-white p-4 rounded-3xl shadow-2xl",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-white",
    },
  },
  {
    id: 33,
    name: "Futuristic Samurai UI",
    fonts: { primary: "Kanit", secondary: "Noto Sans JP" },
    colors: { primary: "Red", accent: "Black", dark: "Steel gray", light: "White" },
    layout: "Blade-inspired dividers, katana-like panels",
    style: "Cyberpunk + Japanese heritage",
    previewConfig: {
      palette: { bg: "#0A0A0A", text: "#E0E0E0", primary: "#E60023", accent: "#808080", neutral: "#1A1A1A" },
      buttonClasses: "bg-[#E60023] text-white font-bold py-2 px-8 -skew-x-12 hover:bg-red-700 transition-colors",
      cardClasses: "bg-[#1A1A1A] p-4 md:p-6",
      cardPrimaryClasses: "bg-gray-700 text-white p-6",
      containerClasses: "bg-black",
      headerClasses: "font-black text-5xl text-white uppercase tracking-wider",
      tagClasses: "bg-red-900/50 text-red-300 text-xs px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-800/50 hover:bg-gray-700/50",
      inputClasses: "bg-transparent border-b-2 border-gray-700 placeholder:text-gray-500 text-sm py-2 w-full",
      tabClasses: { container: "border-b-2 border-red-800", base: "px-4 py-2 text-sm uppercase", active: "text-red-500 font-bold", inactive: "text-gray-500 hover:text-white" },
      kpiCardClasses: "bg-[#1A1A1A] p-4",
      avatarClasses: "w-9 h-9 rounded-sm",
    },
  },
  {
    id: 34,
    name: "Aurora Borealis UI",
    fonts: { primary: "Raleway", secondary: "Cabin" },
    colors: { primary: "Emerald green", accent: "Violet", dark: "Cyan", light: "Midnight blue" },
    layout: "Wave gradients across backgrounds",
    style: "Atmospheric, flowing light aesthetic",
    previewConfig: {
      palette: { bg: "#000B2C", text: "#E0EFFF", primary: "#22C55E", accent: "#8B5CF6", neutral: "rgba(255, 255, 255, 0.05)" },
      buttonClasses: "bg-white/10 backdrop-blur-sm border border-cyan-400/50 text-cyan-300 font-bold rounded-lg px-6 py-2 hover:bg-cyan-500/30 hover:text-white transition-all",
      cardClasses: "bg-black/30 backdrop-blur-md border border-violet-500/50 rounded-lg p-4 md:p-6",
      cardPrimaryClasses: "bg-green-500/20 text-white p-6 rounded-lg",
      containerClasses: "bg-gradient-to-br from-[#000B2C] to-[#0A1940]",
      headerClasses: "font-bold text-4xl text-white drop-shadow-[0_0_8px_rgba(34,197,94,0.5)]",
      tagClasses: "bg-violet-500/30 text-violet-200 text-xs font-bold px-3 py-1 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/10 rounded-lg border border-cyan-400/50",
      inputClasses: "bg-black/20 border border-cyan-500/50 rounded-lg placeholder:text-cyan-300/50 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-violet-500/50", base: "px-4 py-2 text-sm text-cyan-300", active: "bg-violet-500/20", inactive: "hover:bg-violet-500/10" },
      kpiCardClasses: "bg-black/30 backdrop-blur-md border border-violet-500/50 rounded-lg p-4",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-cyan-500/80",
    },
  },
  {
    id: 35,
    name: "Steampunk UI",
    fonts: { primary: "Cinzel", secondary: "Courier Prime" },
    colors: { primary: "Brass", accent: "Copper", dark: "Leather brown", light: "Ivory" },
    layout: "Gears, rivet frames, ornate dividers",
    style: "Industrial vintage meets adventure",
    previewConfig: {
      palette: { bg: "#F3EADF", text: "#4A2C2A", primary: "#B87333", accent: "#8C483F", neutral: "#D4C5B2" },
      buttonClasses: "bg-gradient-to-b from-[#B87333] to-[#8C483F] text-white font-bold py-2 px-6 rounded-sm border-b-4 border-black/20",
      cardClasses: "bg-[#D4C5B2] p-4 md:p-6 rounded-sm border-2 border-black/20",
      cardPrimaryClasses: "bg-[#8C483F] text-white p-6 rounded-sm",
      containerClasses: "bg-[#F3EADF]",
      headerClasses: "font-bold text-4xl text-black/80 tracking-wider",
      tagClasses: "bg-amber-800 text-white text-xs font-semibold px-3 py-1.5 rounded-sm",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-[#D4C5B2] border-2 border-black/20",
      inputClasses: "bg-[#F3EADF] border border-black/20 rounded-sm placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b-4 border-double border-black/20", base: "px-4 py-2 text-sm", active: "font-bold bg-[#D4C5B2]", inactive: "hover:bg-[#D4C5B2]/50" },
      kpiCardClasses: "bg-[#D4C5B2] p-4 rounded-sm border-2 border-black/20",
      avatarClasses: "w-9 h-9 rounded-sm border-2 border-black/20",
    },
  },
    {
    id: 36,
    name: "Origami Animals UI",
    fonts: { primary: "Nunito", secondary: "Lexend" },
    colors: { primary: "Pastel origami animal palette", accent: "Mint", dark: "Peach", light: "Lilac" },
    layout: "Folded-paper inspired icons",
    style: "Whimsical, geometric, lighthearted",
    previewConfig: {
      palette: { bg: "#FEF9E7", text: "#5D6D7E", primary: "#A3E4D7", accent: "#FADBD8", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#A3E4D7] text-teal-800 font-bold py-2 px-6 rounded-lg hover:bg-teal-300 transition-colors",
      cardClasses: "bg-white p-4 md:p-6 rounded-xl shadow-lg",
      cardPrimaryClasses: "bg-[#FADBD8] text-red-800 p-6 rounded-xl",
      containerClasses: "bg-yellow-50",
      headerClasses: "font-extrabold text-4xl text-gray-700",
      tagClasses: "bg-purple-200 text-purple-800 text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white rounded-lg shadow-md",
      inputClasses: "bg-white border-2 border-gray-200 rounded-lg placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "bg-white p-1 rounded-lg", base: "px-4 py-1 text-sm font-semibold rounded-md", active: "bg-teal-100 text-teal-700", inactive: "hover:bg-gray-100" },
      kpiCardClasses: "bg-white p-4 rounded-xl shadow-lg",
      avatarClasses: "w-9 h-9 rounded-lg",
    },
  },
  {
    id: 37,
    name: "Ocean Tide UI",
    fonts: { primary: "Playfair Display", secondary: "Urbanist" },
    colors: { primary: "Deep navy", accent: "Foam white", dark: "Seafoam green", light: "Coral" },
    layout: "Wave dividers, water ripple animations",
    style: "Calm, coastal-inspired",
    previewConfig: {
      palette: { bg: "#F0F4F8", text: "#0F172A", primary: "#0A2463", accent: "#3D84A8", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#0A2463] text-white font-semibold py-2 px-5 rounded-lg hover:bg-blue-900 transition-colors",
      cardClasses: "bg-white/90 backdrop-blur-sm p-4 md:p-6 rounded-xl shadow-md",
      cardPrimaryClasses: "bg-[#3D84A8] text-white p-6 rounded-xl",
      containerClasses: "bg-slate-100",
      headerClasses: "font-bold text-5xl text-slate-900",
      tagClasses: "bg-cyan-100 text-cyan-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white rounded-lg shadow-sm",
      inputClasses: "bg-white border border-gray-200 rounded-lg placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-500", active: "text-blue-800 border-b-2 border-blue-800", inactive: "hover:bg-slate-50" },
      kpiCardClasses: "bg-white/90 p-4 rounded-xl shadow-md",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 38,
    name: "Galactic Core UI",
    fonts: { primary: "JetBrains Mono", secondary: "Space Mono" },
    colors: { primary: "Black", accent: "Fiery orange", dark: "Galaxy purple", light: "White stars" },
    layout: "Orbital rings, planet-like buttons",
    style: "Cosmic, bold, scientific",
    previewConfig: {
      palette: { bg: "#000000", text: "#FFFFFF", primary: "#FF4500", accent: "#9400D3", neutral: "#1A1A1A" },
      buttonClasses: "bg-transparent border border-orange-500 text-orange-500 font-bold px-6 py-2 rounded-full hover:bg-orange-500 hover:text-black",
      cardClasses: "bg-[#1A1A1A]/80 backdrop-blur-sm border border-purple-500/30 p-4 md:p-6 rounded-lg",
      cardPrimaryClasses: "bg-purple-500 text-white p-6 rounded-lg",
      containerClasses: "bg-black",
      headerClasses: "font-bold text-4xl text-white",
      tagClasses: "bg-purple-500/50 text-purple-200 text-xs font-bold px-3 py-1 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/5 rounded-full border border-orange-500/30",
      inputClasses: "bg-black/20 border border-gray-700 rounded-lg placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-700", base: "px-4 py-2 text-sm", active: "text-orange-500", inactive: "hover:bg-gray-800" },
      kpiCardClasses: "bg-[#1A1A1A]/80 p-4 rounded-lg border border-purple-500/30",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-orange-500/50",
    },
  },
    {
    id: 39,
    name: "Retro Pixel Graffiti UI",
    fonts: { primary: "Press Start 2P", secondary: "Bebas Neue" },
    colors: { primary: "Neon spray palette", accent: "Magenta", dark: "Cyan", light: "Lime" },
    layout: "Pixel art layered with graffiti textures",
    style: "Urban nostalgia + street art",
    previewConfig: {
      palette: { bg: "#1A1A1A", text: "#FFFFFF", primary: "#FF00FF", accent: "#00FFFF", neutral: "#333333" },
      buttonClasses: "bg-[#FF00FF] text-black text-lg px-6 py-1 hover:bg-magenta-400",
      cardClasses: "bg-[#333333] p-4 border-4 border-dashed border-[#00FFFF]",
      cardPrimaryClasses: "bg-lime-400 text-black p-4",
      containerClasses: "bg-[#1A1A1A]",
      headerClasses: "text-3xl text-lime-300",
      tagClasses: "bg-cyan-400 text-black text-xl px-4",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/10 border-2 border-white/50",
      inputClasses: "bg-transparent border-b-2 border-dotted border-white/50 text-lg p-2 w-full",
      tabClasses: { container: "border-b-4 border-dashed border-lime-400", base: "px-4 py-1 text-xl", active: "bg-[#FF00FF] text-black", inactive: "hover:bg-white/20" },
      kpiCardClasses: "bg-[#333333] p-4 border-2 border-white/80",
      avatarClasses: "w-9 h-9 rounded-none border-2 border-cyan-400",
    },
  },
  {
    id: 40,
    name: "Origami Data Dashboard",
    fonts: { primary: "Inter", secondary: "Inter" },
    colors: { primary: "White", accent: "Cyan", dark: "Red", light: "Black" },
    layout: "Folded card widgets, sharp grids",
    style: "Origami + SaaS dashboard",
    previewConfig: {
      palette: { bg: "#F4F7FA", text: "#1A202C", primary: "#00A4E6", accent: "#E53E3E", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#00A4E6] text-white font-semibold py-2 px-5 rounded-md hover:bg-cyan-600 transition-colors",
      cardClasses: "bg-white p-4 md:p-6 rounded-lg shadow-sm border border-gray-200",
      cardPrimaryClasses: "bg-red-500 text-white p-6 rounded-lg",
      containerClasses: "bg-slate-100",
      headerClasses: "font-bold text-4xl text-gray-800",
      tagClasses: "bg-red-100 text-red-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white border border-gray-200 rounded-md",
      inputClasses: "bg-white border border-gray-300 rounded-md placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-500", active: "text-cyan-600 font-semibold border-b-2 border-cyan-600", inactive: "hover:bg-gray-50" },
      kpiCardClasses: "bg-white p-4 rounded-lg shadow-sm border border-gray-200",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 41,
    name: "Crystal Cave UI",
    fonts: { primary: "Quicksand", secondary: "Manrope" },
    colors: { primary: "Amethyst purple", accent: "Quartz pink", dark: "Sapphire blue", light: "White" },
    layout: "Faceted crystal backgrounds",
    style: "Magical, mysterious, luminous",
    previewConfig: {
      palette: { bg: "#1D1626", text: "#EAE6F0", primary: "#A450E5", accent: "#F4ABC4", neutral: "rgba(255,255,255,0.05)" },
      buttonClasses: "bg-gradient-to-r from-[#A450E5] to-[#7342E1] text-white font-bold py-2 px-6 rounded-lg shadow-lg hover:shadow-xl",
      cardClasses: "bg-white/10 backdrop-blur-lg p-4 md:p-6 rounded-xl border border-white/20",
      cardPrimaryClasses: "bg-[#F4ABC4]/80 text-pink-900 p-6 rounded-xl",
      containerClasses: "bg-[#1D1626]",
      headerClasses: "font-bold text-4xl text-white",
      tagClasses: "bg-blue-400/20 text-blue-200 text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/10 rounded-lg",
      inputClasses: "bg-white/5 backdrop-blur-sm border border-white/10 rounded-lg placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-white/10", base: "px-4 py-2 text-sm", active: "text-purple-300 font-bold", inactive: "text-gray-400 hover:text-white" },
      kpiCardClasses: "bg-white/10 backdrop-blur-lg p-4 rounded-xl border border-white/20",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-white/20",
    },
  },
  {
    id: 42,
    name: "Underwater Coral UI",
    fonts: { primary: "DM Sans", secondary: "Cormorant Garamond" },
    colors: { primary: "Coral red", accent: "Sea blue", dark: "Sandy beige", light: "Teal" },
    layout: "Flowing coral shapes, organic dividers",
    style: "Aquatic, lively, tropical",
    previewConfig: {
      palette: { bg: "#EBF4F8", text: "#00425A", primary: "#FF6F61", accent: "#1F8A70", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#FF6F61] text-white font-bold py-2 px-6 rounded-full hover:bg-red-500 transition-colors",
      cardClasses: "bg-white/80 backdrop-blur-sm p-4 md:p-6 rounded-2xl",
      cardPrimaryClasses: "bg-[#1F8A70] text-white p-6 rounded-2xl",
      containerClasses: "bg-[#EBF4F8]",
      headerClasses: "font-bold text-4xl text-blue-900",
      tagClasses: "bg-teal-100 text-teal-800 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white rounded-full shadow-sm",
      inputClasses: "bg-white border border-gray-200 rounded-full px-4 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-500", active: "text-red-500", inactive: "hover:bg-blue-50" },
      kpiCardClasses: "bg-white/80 p-4 rounded-2xl",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 43,
    name: "Ink & Wash UI",
    fonts: { primary: "Noto Serif", secondary: "Literata" },
    colors: { primary: "Black ink", accent: "Rice paper white", dark: "Muted red accents", light: "Gray" },
    layout: "Watercolor textures, brushstroke dividers",
    style: "Traditional East Asian art aesthetic",
    previewConfig: {
      palette: { bg: "#F5F5F5", text: "#222222", primary: "#A52A2A", accent: "#808080", neutral: "#FFFFFF" },
      buttonClasses: "bg-transparent border border-black text-black font-semibold px-6 py-2 rounded-sm hover:bg-black hover:text-white",
      cardClasses: "bg-white/90 p-4 md:p-6 rounded-sm",
      cardPrimaryClasses: "bg-[#A52A2A] text-white p-6 rounded-sm",
      containerClasses: "bg-[#F5F5F5]",
      headerClasses: "font-bold text-4xl",
      tagClasses: "bg-gray-200 text-black text-xs px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 hover:bg-gray-100",
      inputClasses: "bg-white border-b-2 border-gray-300 placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm", active: "font-bold border-b-2 border-black", inactive: "text-gray-500 hover:text-black" },
      kpiCardClasses: "bg-white/90 p-4 rounded-sm",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 44,
    name: "Festival Glow UI",
    fonts: { primary: "Poppins", secondary: "Righteous" },
    colors: { primary: "Neon pink", accent: "Gold", dark: "Emerald", light: "Violet" },
    layout: "Bold festival-inspired patterns",
    style: "Celebration, energy, nightlife",
    previewConfig: {
      palette: { bg: "#10002B", text: "#FFFFFF", primary: "#E02998", accent: "#FFD700", neutral: "#240046" },
      buttonClasses: "bg-gradient-to-r from-pink-500 to-yellow-500 text-white font-bold py-3 px-6 rounded-full shadow-lg hover:scale-105 transition-transform",
      cardClasses: "bg-[#240046]/80 backdrop-blur-md border border-violet-500/50 p-4 md:p-6 rounded-lg",
      cardPrimaryClasses: "bg-emerald-500 text-white p-6 rounded-lg",
      containerClasses: "bg-[#10002B]",
      headerClasses: "font-black text-5xl text-white uppercase drop-shadow-[0_0_8px_#E02998]",
      tagClasses: "bg-yellow-400/80 text-black text-sm font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/10 rounded-full",
      inputClasses: "bg-black/20 border border-violet-500/50 rounded-full px-4 placeholder:text-gray-400 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-violet-500/50", base: "px-4 py-2 text-md uppercase", active: "text-pink-400", inactive: "hover:text-white" },
      kpiCardClasses: "bg-[#240046]/80 p-4 rounded-lg border border-violet-500/50",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-pink-500/80",
    },
  },
    {
    id: 45,
    name: "Cloudscape UI",
    fonts: { primary: "Lato", secondary: "Inter" },
    colors: { primary: "Sky blue", accent: "Fluffy white", dark: "Pastel gradients", light: "Soft gray" },
    layout: "Soft rounded panels, cloud-like shapes",
    style: "Uplifting, dreamy, calm",
    previewConfig: {
      palette: { bg: "#F0F9FF", text: "#374151", primary: "#87CEEB", accent: "#FFDAB9", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#87CEEB] text-white font-semibold py-2 px-5 rounded-full shadow-md hover:bg-sky-500 transition-colors",
      cardClasses: "bg-white/80 backdrop-blur-xl p-4 md:p-6 rounded-2xl shadow-lg shadow-sky-100/50",
      cardPrimaryClasses: "bg-peach-300 text-peach-800 p-6 rounded-2xl",
      containerClasses: "bg-sky-50",
      headerClasses: "font-bold text-4xl text-gray-800",
      tagClasses: "bg-orange-100 text-orange-700 text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white rounded-xl shadow-md",
      inputClasses: "bg-white/80 border border-gray-200 rounded-full px-4 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-200", base: "px-4 py-2 text-sm text-gray-500", active: "text-sky-600", inactive: "hover:text-sky-500" },
      kpiCardClasses: "bg-white/80 p-4 rounded-2xl shadow-lg",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 46,
    name: "Origami Techno UI",
    fonts: { primary: "Space Grotesk", secondary: "Orbitron" },
    colors: { primary: "White", accent: "Neon cyan", dark: "Graphite black", light: "Gray" },
    layout: "Folded card panels, 3D UI blocks",
    style: "Futuristic origami hybrid",
    previewConfig: {
      palette: { bg: "#111111", text: "#FFFFFF", primary: "#00FFFF", accent: "#CCCCCC", neutral: "#222222" },
      buttonClasses: "bg-transparent border-2 border-cyan-400 text-cyan-400 font-bold px-6 py-2 hover:bg-cyan-400 hover:text-black",
      cardClasses: "bg-[#222222] p-4 md:p-6",
      cardPrimaryClasses: "bg-gray-400 text-black p-6",
      containerClasses: "bg-black",
      headerClasses: "font-black text-4xl text-white uppercase tracking-widest",
      tagClasses: "bg-cyan-400/50 text-cyan-200 text-xs font-bold px-3 py-1",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-800",
      inputClasses: "bg-transparent border-b border-gray-700 placeholder:text-gray-500 text-sm py-2 w-full",
      tabClasses: { container: "border-b border-cyan-700", base: "px-4 py-2 text-sm uppercase", active: "text-cyan-400", inactive: "hover:text-white" },
      kpiCardClasses: "bg-[#222222] p-4",
      avatarClasses: "w-9 h-9",
    },
  },
  {
    id: 47,
    name: "Gothic Elegance UI",
    fonts: { primary: "Cinzel Decorative", secondary: "Cinzel" },
    colors: { primary: "Deep crimson", accent: "Gold", dark: "Black", light: "Ivory" },
    layout: "Ornate borders, cathedral-inspired spacing",
    style: "Medieval yet elegant",
    previewConfig: {
      palette: { bg: "#1A1A1A", text: "#E5E5E5", primary: "#8B0000", accent: "#FFD700", neutral: "#2A2A2A" },
      buttonClasses: "bg-transparent border border-red-800 text-red-300 font-bold px-8 py-3 hover:bg-red-800 hover:text-white",
      cardClasses: "bg-[#2A2A2A] p-4 md:p-6 border-2 border-double border-yellow-700/50",
      cardPrimaryClasses: "bg-red-900 text-white p-6",
      containerClasses: "bg-black",
      headerClasses: "font-bold text-5xl text-white tracking-widest",
      tagClasses: "bg-yellow-800/50 text-yellow-300 text-xs px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 border border-yellow-700/50",
      inputClasses: "bg-transparent border-b border-yellow-700/50 placeholder:text-gray-500 py-2 w-full",
      tabClasses: { container: "border-b border-double border-yellow-700/50", base: "px-4 py-2 text-sm", active: "text-red-400 font-bold", inactive: "hover:text-white" },
      kpiCardClasses: "bg-[#2A2A2A] p-4 border border-yellow-700/50",
      avatarClasses: "w-9 h-9 rounded-sm border-2 border-yellow-700/50",
    },
  },
  {
    id: 48,
    name: "Chromatic Noise UI",
    fonts: { primary: "Inter", secondary: "Inter" },
    colors: { primary: "Static TV gradients", accent: "Neon overlays", dark: "Chaotic", light: "Edgy" },
    layout: "Distorted glitch UI, noisy textures",
    style: "Experimental, edgy, chaotic",
    previewConfig: {
      palette: { bg: "#000000", text: "#FFFFFF", primary: "#00FF00", accent: "#FF00FF", neutral: "#1A1A1A" },
      buttonClasses: "bg-white/10 text-white font-mono px-5 py-2 hover:bg-white/20",
      cardClasses: "bg-[#1A1A1A] p-4 md:p-6",
      cardPrimaryClasses: "bg-green-500 text-black p-6",
      containerClasses: "bg-black",
      headerClasses: "font-black text-4xl text-green-400",
      tagClasses: "bg-magenta-500 text-white text-xs px-2 py-1",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-800",
      inputClasses: "bg-transparent border border-gray-700 font-mono placeholder:text-gray-500 p-2 w-full",
      tabClasses: { container: "border-b border-gray-700", base: "px-4 py-2 text-sm font-mono", active: "bg-gray-700", inactive: "hover:bg-gray-800" },
      kpiCardClasses: "bg-[#1A1A1A] p-4",
      avatarClasses: "w-9 h-9 rounded-none",
    },
  },
  {
    id: 49,
    name: "Midnight Safari UI",
    fonts: { primary: "Archivo", secondary: "Manrope" },
    colors: { primary: "Dark jungle green", accent: "Golden yellow", dark: "Zebra black & white", light: "Brown" },
    layout: "Animal print accents, organic borders",
    style: "Wild, adventurous, exotic",
    previewConfig: {
      palette: { bg: "#1F2421", text: "#EAE7DC", primary: "#FFD700", accent: "#FFFFFF", neutral: "#2A312D" },
      buttonClasses: "bg-[#FFD700] text-black font-bold py-2 px-6 rounded-lg hover:bg-yellow-400",
      cardClasses: "bg-[#2A312D] p-4 md:p-6 rounded-lg",
      cardPrimaryClasses: "bg-white text-black p-6 rounded-lg",
      containerClasses: "bg-[#1F2421]",
      headerClasses: "font-extrabold text-4xl text-white",
      tagClasses: "bg-yellow-800/50 text-yellow-300 text-xs px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-black/20 rounded-lg",
      inputClasses: "bg-black/20 border border-gray-700 rounded-lg placeholder:text-gray-500 p-2 w-full",
      tabClasses: { container: "border-b border-gray-700", base: "px-4 py-2 text-sm", active: "text-yellow-400 font-bold", inactive: "hover:text-white" },
      kpiCardClasses: "bg-[#2A312D] p-4 rounded-lg",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  // Duplicates from user prompt, added with new IDs
  {
    id: 50,
    name: "Liquid Metal UI",
    fonts: { primary: "Inter", secondary: "Inter" },
    colors: { primary: "Polished chrome", accent: "Molten silver", dark: "Black", light: "White" },
    layout: "Fluid metallic buttons, reflective surfaces",
    style: "Glossy, futuristic, immersive",
    previewConfig: {
      palette: { bg: "#111111", text: "#FFFFFF", primary: "#B0B0B0", accent: "#FFFFFF", neutral: "#222222" },
      buttonClasses: "bg-gradient-to-b from-gray-300 to-gray-500 text-black font-semibold py-2 px-5 rounded-lg shadow-md border border-gray-600 hover:from-gray-400 hover:to-gray-600",
      cardClasses: "bg-gradient-to-b from-gray-800 to-gray-900 border border-gray-700 p-4 md:p-6 rounded-xl",
      cardPrimaryClasses: "bg-gray-700 text-white p-6 rounded-xl",
      containerClasses: "bg-[#111111]",
      headerClasses: "font-bold text-4xl text-white",
      tagClasses: "bg-gray-600 text-white text-xs font-semibold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-800 rounded-lg border border-gray-700",
      inputClasses: "bg-gray-900 border border-gray-700 rounded-lg placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-gray-700", base: "px-4 py-2 text-sm text-gray-400", active: "text-white", inactive: "hover:bg-gray-800" },
      kpiCardClasses: "bg-gray-800/50 p-4 rounded-xl border border-gray-700",
      avatarClasses: "w-9 h-9 rounded-full",
    },
  },
  {
    id: 51,
    name: "Solar Eclipse UI",
    fonts: { primary: "Manrope", secondary: "Inter" },
    colors: { primary: "Black", accent: "Golden yellow", dark: "Twilight blue", light: "Crimson" },
    layout: "Circular modules, gradient light rings",
    style: "Celestial, cosmic interface",
    previewConfig: {
      palette: { bg: "#000000", text: "#FFFFFF", primary: "#FFD700", accent: "#FF4500", neutral: "#191970" },
      buttonClasses: "bg-transparent border-2 border-yellow-400 text-yellow-400 font-bold px-6 py-2 rounded-full shadow-[0_0_10px_#FFD700] hover:bg-yellow-400 hover:text-black transition-all",
      cardClasses: "bg-blue-900/30 backdrop-blur-md border border-yellow-400/30 p-4 md:p-6 rounded-full",
      cardPrimaryClasses: "bg-yellow-400 text-black p-6 rounded-full",
      containerClasses: "bg-black",
      headerClasses: "font-black text-4xl text-white drop-shadow-[0_0_5px_#FFD700]",
      tagClasses: "bg-red-500/30 text-red-300 text-xs font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/5 rounded-full border border-yellow-400/30",
      inputClasses: "bg-black/20 border border-yellow-400/30 rounded-full px-4 placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-yellow-400/30", base: "px-4 py-2 text-sm rounded-full", active: "bg-yellow-400/20 text-yellow-300", inactive: "text-gray-400 hover:text-white" },
      kpiCardClasses: "bg-blue-900/30 p-4 rounded-full border border-yellow-400/30",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-yellow-400/50",
    },
  },
    {
    id: 52,
    name: "Candy Pop UI",
    fonts: { primary: "Baloo 2", secondary: "Fredoka" },
    colors: { primary: "Bubblegum pink", accent: "Lemon yellow", dark: "Mint green", light: "Sky blue" },
    layout: "Rounded bubbly elements, candy-like buttons",
    style: "Playful, childlike, cheerful",
    previewConfig: {
      palette: { bg: "#F0F9FF", text: "#4B5563", primary: "#F9A8D4", accent: "#FDE047", neutral: "#FFFFFF" },
      buttonClasses: "bg-[#F9A8D4] text-pink-800 font-bold text-lg py-3 px-6 rounded-full shadow-lg border-2 border-white hover:-translate-y-1 transition-all",
      cardClasses: "bg-white p-6 rounded-3xl shadow-2xl",
      cardPrimaryClasses: "bg-[#FDE047] text-yellow-800 p-6 rounded-3xl shadow-2xl",
      containerClasses: "bg-sky-100",
      headerClasses: "font-extrabold text-5xl text-gray-700",
      tagClasses: "bg-green-200 text-green-800 text-sm font-bold px-3 py-1.5 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-12 h-12 bg-white rounded-2xl shadow-lg",
      inputClasses: "bg-white border-2 border-gray-200 rounded-full placeholder:text-gray-400 text-md p-2 px-4 w-full",
      tabClasses: { container: "bg-white p-1 rounded-full shadow-inner", base: "px-4 py-1.5 text-md font-bold rounded-full", active: "bg-pink-100 text-pink-600", inactive: "text-gray-500 hover:bg-pink-50" },
      kpiCardClasses: "bg-white p-4 rounded-3xl shadow-2xl",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-white",
    },
  },
  {
    id: 53,
    name: "Futuristic Samurai UI",
    fonts: { primary: "Kanit", secondary: "Noto Sans JP" },
    colors: { primary: "Red", accent: "Black", dark: "Steel gray", light: "White" },
    layout: "Blade-inspired dividers, katana-like panels",
    style: "Cyberpunk + Japanese heritage",
    previewConfig: {
      palette: { bg: "#0A0A0A", text: "#E0E0E0", primary: "#E60023", accent: "#808080", neutral: "#1A1A1A" },
      buttonClasses: "bg-[#E60023] text-white font-bold py-2 px-8 -skew-x-12 hover:bg-red-700 transition-colors",
      cardClasses: "bg-[#1A1A1A] p-4 md:p-6",
      cardPrimaryClasses: "bg-gray-700 text-white p-6",
      containerClasses: "bg-black",
      headerClasses: "font-black text-5xl text-white uppercase tracking-wider",
      tagClasses: "bg-red-900/50 text-red-300 text-xs px-3 py-1.5",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-gray-800/50 hover:bg-gray-700/50",
      inputClasses: "bg-transparent border-b-2 border-gray-700 placeholder:text-gray-500 text-sm py-2 w-full",
      tabClasses: { container: "border-b-2 border-red-800", base: "px-4 py-2 text-sm uppercase", active: "text-red-500 font-bold", inactive: "text-gray-500 hover:text-white" },
      kpiCardClasses: "bg-[#1A1A1A] p-4",
      avatarClasses: "w-9 h-9 rounded-sm",
    },
  },
  {
    id: 54,
    name: "Aurora Borealis UI",
    fonts: { primary: "Raleway", secondary: "Cabin" },
    colors: { primary: "Emerald green", accent: "Violet", dark: "Cyan", light: "Midnight blue" },
    layout: "Wave gradients across backgrounds",
    style: "Atmospheric, flowing light aesthetic",
    previewConfig: {
      palette: { bg: "#000B2C", text: "#E0EFFF", primary: "#22C55E", accent: "#8B5CF6", neutral: "rgba(255, 255, 255, 0.05)" },
      buttonClasses: "bg-white/10 backdrop-blur-sm border border-cyan-400/50 text-cyan-300 font-bold rounded-lg px-6 py-2 hover:bg-cyan-500/30 hover:text-white transition-all",
      cardClasses: "bg-black/30 backdrop-blur-md border border-violet-500/50 rounded-lg p-4 md:p-6",
      cardPrimaryClasses: "bg-green-500/20 text-white p-6 rounded-lg",
      containerClasses: "bg-gradient-to-br from-[#000B2C] to-[#0A1940]",
      headerClasses: "font-bold text-4xl text-white drop-shadow-[0_0_8px_rgba(34,197,94,0.5)]",
      tagClasses: "bg-violet-500/30 text-violet-200 text-xs font-bold px-3 py-1 rounded-full",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-white/10 rounded-lg border border-cyan-400/50",
      inputClasses: "bg-black/20 border border-cyan-500/50 rounded-lg placeholder:text-cyan-300/50 text-sm p-2 w-full",
      tabClasses: { container: "border-b border-violet-500/50", base: "px-4 py-2 text-sm text-cyan-300", active: "bg-violet-500/20", inactive: "hover:bg-violet-500/10" },
      kpiCardClasses: "bg-black/30 backdrop-blur-md border border-violet-500/50 rounded-lg p-4",
      avatarClasses: "w-9 h-9 rounded-full border-2 border-cyan-500/80",
    },
  },
  {
    id: 55,
    name: "Steampunk UI",
    fonts: { primary: "Cinzel", secondary: "Courier Prime" },
    colors: { primary: "Brass", accent: "Copper", dark: "Leather brown", light: "Ivory" },
    layout: "Gears, rivet frames, ornate dividers",
    style: "Industrial vintage meets adventure",
    previewConfig: {
      palette: { bg: "#F3EADF", text: "#4A2C2A", primary: "#B87333", accent: "#8C483F", neutral: "#D4C5B2" },
      buttonClasses: "bg-gradient-to-b from-[#B87333] to-[#8C483F] text-white font-bold py-2 px-6 rounded-sm border-b-4 border-black/20",
      cardClasses: "bg-[#D4C5B2] p-4 md:p-6 rounded-sm border-2 border-black/20",
      cardPrimaryClasses: "bg-[#8C483F] text-white p-6 rounded-sm",
      containerClasses: "bg-[#F3EADF]",
      headerClasses: "font-bold text-4xl text-black/80 tracking-wider",
      tagClasses: "bg-amber-800 text-white text-xs font-semibold px-3 py-1.5 rounded-sm",
      iconButtonClasses: "flex items-center justify-center w-10 h-10 bg-[#D4C5B2] border-2 border-black/20",
      inputClasses: "bg-[#F3EADF] border border-black/20 rounded-sm placeholder:text-gray-500 text-sm p-2 w-full",
      tabClasses: { container: "border-b-4 border-double border-black/20", base: "px-4 py-2 text-sm", active: "font-bold bg-[#D4C5B2]", inactive: "hover:bg-[#D4C5B2]/50" },
      kpiCardClasses: "bg-[#D4C5B2] p-4 rounded-sm border-2 border-black/20",
      avatarClasses: "w-9 h-9 rounded-sm border-2 border-black/20",
    },
  }
];